# MQTT Clients Configuration
# Define all MQTT clients along with the topics they subscribe to.

logging:
  default_level: INFO
  loggers:
    mqtt_flow:
      level: INFO
    mqtt_client_client1:
      level: INFO
    mqtt_client_client2:
      level: INFO
    mqtt_on_msg_callback:
      level: INFO
    mqtt_on_connect_callback:
      level: INFO
    mqtt_on_disconnect_callback:
      level: INFO
    executor_pools:
      level: INFO
    mqtt_rule:
      level: INFO
    persistence:
      level: INFO
    mqtt_persistence:
      level: INFO

mqtt_clients:
  - client_name: 'client1'
    sub_topics:
      - test/topic1
    persistence_config:
      name: simple_persistence
      main_path: '/tmp/persistence'
      rules:
        - topic: 'test/topic1'
          reupload_topic_formatters:
            - prefix: old

  - client_name: 'client2'
    sub_topics:
      - test/topic2
      - test/topic3
      - old/test/topic1

tasks_queues:
  - name: 'client1_queue'
    size: 5
    pool: 'pool1'
  - name: 'client2_queue'
    size: 10
    pool: 'pool1'

pools:
  - name: 'pool1'
    max_workers: 5
    type: 'simple_thread'

# Rules Configuration
# Rules can specify a direct callback for simple tasks or an action referring to a processing chain.
rules:
  # - name: 'simple_rule1'
  #   source_client_name: 'client1'
  #   topic: 'test/topic1'
  #   task:
  #     path: 'task.Task'
  #     queue_name: client1_queue
  - name: 'relay_rule'
    source_client_name: 'client2'
    topic: 'test/topic2'
    task:
      path: 'mqtt_flow.core.task.RelayMessage'
      queue_name: client2_queue
      client_to_publish: 'client1'
      topic_to_publish: 'test/topic3'
