# MQTT Clients Configuration
# Define all MQTT clients along with the topics they subscribe to.
mqtt_clients:
  - client_name: 'client1'
    sub_topics:
      - test/topic1
  - client_name: 'client2'
    sub_topics:
      - test/topic2
      - test/topic3

tasks_queues:
  - name: 'client1_queue'
    size: 5
    pool: 'pool1'
  - name: 'client2_queue'
    size: 10
    pool: 'pool1'

pools:
  - name: 'pool1'
    max_workers: 5
    type: 'simple_thread'


# Rules Configuration
# Rules can specify a direct callback for simple tasks or an action referring to a processing chain.
rules:
  # - name: 'simple_rule1'
  #   source_client_name: 'client1'
  #   topic: 'test/topic1'
  #   task:
  #     path: 'task.Task'
  #     queue_name: client1_queue
  - name: 'relay_rule'
    source_client_name: 'client2'
    topic: 'test/topic2'
    task:
      path: 'mqtt_flow.core.task.RelayMessage'
      queue_name: client2_queue
      client_to_publish: 'client1'
      topic_to_publish: 'test/topic3'
